### ISSUE TITLE
Unused arguments

### ISSUE THREAD

**Issue by jieeewu** [stephenslab/mr.mash.alpha#1]
Hello,
I have encountered the following error while using the <compute_data_driven_covs> and <mr.mash> function, the reason I found is because of the version of the "flashier" package. How can I fix it.

S0_data_driven <- compute_data_driven_covs(sumstats=univ_sumstats,n_pcs=3)
Error: 'flash.init' is not an exported object from 'namespace:flashier'

**Comment by pcarbo** [comment]
@willwerscheid Could you also please help update `mr.mash.alpha::compute_cov_flash` to align with the latest version of `flashier`?

**Comment by fmorgante** [comment]
@jieeewu That issue is due to some recent renaming of functions in a dependency. Once we are done fixing the downstream effects, we will ask you to update mashr, flashier, and mr.mash.alpha to the latest versions.

**Comment by willwerscheid** [comment]
since `compute_cov_flash()` calls into `mashr::cov_flash()`, it should suffice to update `mashr` no?

**Comment by willwerscheid** [comment]
@pcarbo should be good to go now. might need additional testing, as i did not do anything other than running `R CMD check`

**Comment by pcarbo** [comment]
@jieeewu Please update mashr, flashier and mr.mash.alpha to the latest versions that are available on GitHub.

**Comment by jieeewu** [comment]
It's working. Thank you.
