### ISSUE TITLE
Some details of input file

### ISSUE THREAD

**Issue by jieeewu** [stephenslab/mr.mash.alpha#3]
Hi, I have some details I'd like to ask.
(1) When I use the real genotype data as the input file for mr.mash.alpha, since the genotypes are recoded as 0/1/2, isn't it necessary to scale first, and your source code provides the code, i.e.:
scale_fast2 <- function(M, scale=TRUE, na.rm=TRUE){...}

I would like to ask if it is ok to operate like this if my genotype data is stored in 'dat_list$X':
scale_fast2(dat_list$X, scale=FALSE)$M

(2) Continuing from above, in the example you provided scale_fast2(dat_list$X, scale=FALSE)$M the scale is FALSE, while scale_fast2 <- function(M, scale=TRUE, na.rm=TRUE){...}
In the scale is set to TRUE, what is the difference between these two.

**Comment by fmorgante** [comment]
scale_fast2() is only used internally, so I'm not sure which example you are referring to. You can choose whether to standardize X with the 'standardize' argument in mr.mash().

**Comment by jieeewu** [comment]
Thank you very much for your prompt reply, I have some more questions for you:
(1) When specifying the command：

 ``````
univ_sumstats <- compute_univariate_sumstats(Xtrain, Ytrain,
                   standardize=TRUE, standardize.response=FALSE)
``````

an error is reported:

**Error:** Column 32417 has 0 standard deviation

I found the reason is because all the genotypes of the SNPs in column 32417 are the same. How can I solve this problem.

(2) Is it recommended to use 'compute_data_driven_covs' instead of 'compute_canonical_covs' when using real datasets?

**Comment by fmorgante** [comment]
(1) SNPs with no variation should be filtered out before any analysis.
(2) The canonical covariance matrices are meant to capture *general* patterns of sharing and specificity and are the same across datasets. Data-driven covariance matrices are meant to capture patterns of sharing and specificity that are *specific* to the data at hand. I recommend looking at [Urbut et al.](https://www.nature.com/articles/s41588-018-0268-8) for a detailed description of this. Also, if you are analyzing gene expression, you might want to compute your data-driven matrices borrowing strength across genes following the procedure explained in the same reference.

**Comment by pcarbo** [comment]
@jieeewu What are sizes of X and Y here?

**Comment by jieeewu** [comment]
Hello there.
(1) Sorry I didn't state clearly, the genotypes of the SNPs are all 1, i.e. all heterozygous, according to the filtering conditions provided in the article, I set --maf 0.05 and --geno 0.05, but the maf of the SNPs with genotypes all 1 is 0.5, is it a good idea to add some conditions to filter out these SNPs.
(2) X is a matrix of 200 * 40000, assuming that there are 40000 SNPs within 1Mb upstream and downstream of the gene TSS, and Y is a matrix of 200 * 4, i.e., the expression residuals of a gene in 4 tissues in 200 individuals

**Comment by fmorgante** [comment]
(1) In the mr.mash paper, we also filter for variance of genotypes. In any regression context, predictors that do not vary cannot contribute to variability in the response, thus they should be removed. You can persuade yourself by running the following code:

```
set.seed(1)
y <- rnorm(100)
x <- rep(1, 100)
summary(lm(y ~ x))
```

**Comment by jieeewu** [comment]
Sorry to interrupt again.
I've realized that the consideration of genotypes variance is indeed necessary. 
This is because errors can occur even when the genotypes of the SNP are only 0 and 1, and the ratio is 1:199，
`Error in summary(fit)$coefficients[2, 1] : subscript out of bounds`

My question is, how should the genotypes variance be filtered?

**Comment by fmorgante** [comment]
That's an arbitrary decision that you have to make, in a similar way to choosing a MAF threshold or missing genotype rate threshold.
